name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Enables manual trigger for production deployment

jobs:
  # Job to run linting and testing on every commit
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [frontend, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ${{ matrix.directory }}/package-lock.json

      - name: Install dependencies
        run: |
          cd ${{ matrix.directory }}
          npm ci

      - name: Run linting
        run: |
          cd ${{ matrix.directory }}
          npm run lint

      - name: Run tests
        run: |
          cd ${{ matrix.directory }}
          npm run test

  # Job to deploy to staging when merged to main
  deploy-staging:
    runs-on: ubuntu-latest
    needs: test-and-lint
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          echo "🚀 Deploy staging in progress"
          # Add your staging deployment commands here
          # Example: kubectl apply -f k8s/staging/
          # Example: docker build -t myapp:staging .
          echo "✅ Staging deployment completed"

  # Job to deploy to production (manual trigger only)
  deploy-production:
    runs-on: ubuntu-latest
    needs: test-and-lint
    if: github.event_name == 'workflow_dispatch'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "🚀 Deploy production in progress"
          # Add your production deployment commands here
          # Example: kubectl apply -f k8s/production/
          # Example: docker build -t myapp:prod .
          echo "✅ Production deployment completed"
